###############################################
# General Particle Source (GPS) configuration #
###############################################

/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

###############################################
# 1. Particle type
###############################################

/gps/particle pi-

###############################################
# 2. Energy (GeV)
###############################################

/gps/energy 50 GeV

###############################################
# 3. Position of beam spot
#    CMSSW: BeamMeanX = 0
#           BeamMeanY = 0
#           BeamPosition = -800 mm
###############################################

# Beam center
/gps/pos/type Beam
/gps/pos/shape Square

# Size of the square equivalent to sigma
# sigmaX = sigmaY = 1 μm = 0.001 mm
# CMSSW: uniform distribution in [-0.5σ, +0.5σ]
/gps/pos/halfx 0.0005 mm   # 0.5 μm
/gps/pos/halfy 0.0005 mm   # 0.5 μm

/gps/pos/centre 0.0 0.0 -800.0 mm

###############################################
# 4. Beam direction
# CMSSW: η = 0.5655 y φ = −0.1309 rad
# direction = (Px, Py, Pz)
###############################################

/gps/direction 0.8602 -0.1132 0.4971

###############################################
# 5. Time offset (TimeOffset=0 in CMSSW)
/gps/time 0 ns
###############################################

###################
# Ready to shoot!
###################
/run/beamOn 2
