###############################################
# General Particle Source (GPS) configuration #
###############################################

#/control/alias PARTICLE_ENERGY_GEV 50
#/control/alias PARTICLE_NAME pi-
#/control/alias NEVENTS 5

/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/gps/verbose 1

###############################################
# 1. Particle type
###############################################

/gps/particle {PARTICLE_NAME}

###############################################
# 2. Energy (GeV)
###############################################

/gps/energy {PARTICLE_ENERGY_GEV} GeV

###############################################
# 3. Position of beam spot
/gps/pos/type Point
/gps/pos/centre  -7747.58 1019.99 -1713.07 mm



###############################################
# 4. Beam direction
/gps/direction 0.968448 -0.127499 0.214134


###############################################
# 5. Time offset (TimeOffset=0 in CMSSW)
/gps/time 0 ns
###############################################

/analysis/setFileName HCALTB2006_{PARTICLE_NAME}_{PARTICLE_ENERGY_GEV}_{NEVENTS}evt.root
/analysis/setDefaultFileType root

/run/printProgress 50

###################
# Ready to shoot!
###################
/run/beamOn {NEVENTS}
