/vis/open OGL

/vis/viewer/set/autoRefresh false

/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/style w

# remove beam line and walls from visualization
#/vis/geometry/set/visibility OTBHCal 1 false
/vis/geometry/set/visibility HcalTestBeamLine 1 false
/vis/geometry/set/visibility HcalTestBeamLineDown 1 false
/vis/geometry/set/visibility VMWall1 1 false
/vis/geometry/set/visibility VMWall2 1 false

/vis/scene/add/axes 0 0 0 5 m green

/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/scene/add/trajectories smooth

# draw electrons only
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add e-

# draw charged particles only
/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true

/vis/modeling/trajectories/create/drawByCharge

/vis/viewer/set/viewpointThetaPhi 180. 180.

/vis/viewer/set/background white

# /control/execute gps_singlerun.mac
