universe = docker

docker_image = gitlab-registry.cern.ch/sft/docker/alma9

executable = build.el9.sh

output = build.$(ClusterId).out
error  = build.$(ClusterId).err
log    = build.$(ClusterId).log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = build.el9.sh

transfer_output_files = HCALTB2006/build/gdml_sim

request_cpus = 1

+JobFlavour = "espresso"

queue 1
