universe = docker

docker_image = gitlab-registry.cern.ch/sft/docker/alma9

executable = run.el9.sh

NUM_EVENTS = 80000
NTHREADS = 1

arguments = -g geometryTB2006H2.gdml \
            -pl FTFP_BERT \
            -m gps_singlerun.mac \
            -pname $(pname) \
            -penergy $(penergy) \
            -nevents $(NUM_EVENTS) \
            -nthreads $(NTHREADS) \
            -enableRadialCutSD

output = out.$(pname).$(penergy).out
error  = err.$(pname).$(penergy).err
log    = log.$(ClusterId)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = gdml_sim, ../../data/geometry/geometryTB2006H2.gdml, ../../gps_singlerun.mac

request_cpus   = $(NTHREADS)

+JobFlavour = "nextweek"

+AccountingGroup = "group_u_CMS.u_zh.users"

queue pname, penergy from ../../data/scan/production.scan
