#ifndef YOURTRACKINGACTION_HH
#define YOURTRACKINGACTION_HH

#include "YourParticleInfo.hh"
#include <map>
#include <unordered_map>

#include "G4UserTrackingAction.hh"
#include "globals.hh"

class G4Track;
class G4ParticleDefinition;

class YourTrackingAction : public G4UserTrackingAction
{
public:
    YourTrackingAction();
    virtual ~YourTrackingAction();

    virtual void PostUserTrackingAction(const G4Track * track) override;

    void SetParticleInfoMap(YourParticleInfoMap & m){fParticleInfoMap = m;}
    YourParticleInfoMap fParticleInfoMap;
    const YourParticleInfo & GetParticleInfo(const G4Track * track) const;
    std::map<int, std::pair<const G4ParticleDefinition*,double>> trackIDmap;
    std::unordered_map<std::string,int> fProcNameId = {{"muBrems", 1},
                                                        {"muPairProd", 2},
                                                        {"alphaInelastic", 3},
                                                        {"ionInelastic", 4},
                                                        {"positronNuclear", 5},
                                                        {"anti_lambdaInelastic", 6},
                                                        {"He3Inelastic", 7},
                                                        {"sigma+Inelastic", 8},
                                                        {"tInelastic", 9},
                                                        {"anti_sigma-Inelastic", 10},
                                                        {"electronNuclear", 11},
                                                        {"anti_neutronInelastic", 12},
                                                        {"hIoni", 13},
                                                        {"nCapture", 14},
                                                        {"pi+Inelastic", 15},
                                                        {"sigma-Inelastic", 16},
                                                        {"hBertiniCaptureAtRest", 17},
                                                        {"anti_sigma+Inelastic", 18},
                                                        {"muMinusCaptureAtRest", 19},
                                                        {"eIoni", 20},
                                                        {"eBrem", 21},
                                                        {"Decay", 22},
                                                        {"phot", 23},
                                                        {"compt", 24},
                                                        {"hFritiofCaptureAtRest", 25},
                                                        {"annihil", 26},
                                                        {"muIoni", 27},
                                                        {"neutronInelastic", 28},
                                                        {"hadElastic", 29},
                                                        {"protonInelastic", 30},
                                                        {"photonNuclear", 31},
                                                        {"CoulombScat", 32},
                                                        {"anti_protonInelastic", 33},
                                                        {"kaon0LInelastic", 34},
                                                        {"hPairProd", 35},
                                                        {"kaon+Inelastic", 36},
                                                        {"conv", 37},
                                                        {"dInelastic", 38},
                                                        {"lambdaInelastic", 39},
                                                        {"kaon0SInelastic", 40},
                                                        {"kaon-Inelastic", 41},
                                                        {"pi-Inelastic", 42},
                                                        {"ionIoni", 43},
                                                        {"hBrems", 44},
                                                    };
    // int counter = 0;
    // std::unordered_map<std::string,int> fProcNameId = {	{"B+Inelastic", 0},
    //                                                     {"B-Inelastic", 1},
    //                                                     {"B0Inelastic", 2},
    //                                                     {"Bc+Inelastic", 3},
    //                                                     {"Bc-Inelastic", 4},
    //                                                     {"Bs0Inelastic", 5},
    //                                                     {"CoulombScat", 6},
    //                                                     {"D+Inelastic", 7},
    //                                                     {"D-Inelastic", 8},
    //                                                     {"D0Inelastic", 9},
    //                                                     {"Decay", 10},
    //                                                     {"Ds+Inelastic", 11},
    //                                                     {"Ds-Inelastic", 12},
    //                                                     {"GammaGeneralProc", 13},
    //                                                     {"He3Inelastic", 14},
    //                                                     {"Transportation", 15},
    //                                                     {"TransportationWithMsc", 16},
    //                                                     {"alphaInelastic", 17},
    //                                                     {"annihil", 18},
    //                                                     {"anti_B0Inelastic", 19},
    //                                                     {"anti_Bs0Inelastic", 20},
    //                                                     {"anti_D0Inelastic", 21},
    //                                                     {"anti_He3Inelastic", 22},
    //                                                     {"anti_alphaInelastic", 23},
    //                                                     {"anti_deuteronInelastic", 24},
    //                                                     {"anti_lambdaInelastic", 25},
    //                                                     {"anti_lambda_bInelastic", 26},
    //                                                     {"anti_lambda_c+Inelastic", 27},
    //                                                     {"anti_neutronInelastic", 28},
    //                                                     {"anti_omega-Inelastic", 29},
    //                                                     {"anti_omega_b-Inelastic", 30},
    //                                                     {"anti_omega_c0Inelastic", 31},
    //                                                     {"anti_protonInelastic", 32},
    //                                                     {"anti_sigma+Inelastic", 33},
    //                                                     {"anti_sigma-Inelastic", 34},
    //                                                     {"anti_tritonInelastic", 35},
    //                                                     {"anti_xi-Inelastic", 36},
    //                                                     {"anti_xi0Inelastic", 37},
    //                                                     {"anti_xi_b-Inelastic", 38},
    //                                                     {"anti_xi_b0Inelastic", 39},
    //                                                     {"anti_xi_c+Inelastic", 40},
    //                                                     {"anti_xi_c0Inelastic", 41},
    //                                                     {"dInelastic", 42},
    //                                                     {"eBrem", 43},
    //                                                     {"eIoni", 44},
    //                                                     {"electronNuclear", 45},
    //                                                     {"hBertiniCaptureAtRest", 46},
    //                                                     {"hBrems", 47},
    //                                                     {"hFritiofCaptureAtRest", 48},
    //                                                     {"hIoni", 49},
    //                                                     {"hPairProd", 50},
    //                                                     {"hadElastic", 51},
    //                                                     {"ionInelastic", 52},
    //                                                     {"ionIoni", 53},
    //                                                     {"kaon+Inelastic", 54},
    //                                                     {"kaon-Inelastic", 55},
    //                                                     {"kaon0LInelastic", 56},
    //                                                     {"kaon0SInelastic", 57},
    //                                                     {"lambdaInelastic", 58},
    //                                                     {"lambda_bInelastic", 59},
    //                                                     {"lambda_c+Inelastic", 60},
    //                                                     {"msc", 61},
    //                                                     {"muBrems", 62},
    //                                                     {"muIoni", 63},
    //                                                     {"muMinusCaptureAtRest", 64},
    //                                                     {"muPairProd", 65},
    //                                                     {"muonNuclear", 66},
    //                                                     {"nCapture", 67},
    //                                                     {"neutronInelastic", 68},
    //                                                     {"omega-Inelastic", 69},
    //                                                     {"omega_b-Inelastic", 70},
    //                                                     {"omega_c0Inelastic", 71},
    //                                                     {"pi+Inelastic", 72},
    //                                                     {"pi-Inelastic", 73},
    //                                                     {"positronNuclear", 74},
    //                                                     {"protonInelastic", 75},
    //                                                     {"sigma+Inelastic", 76},
    //                                                     {"sigma-Inelastic", 77},
    //                                                     {"tInelastic", 78},
    //                                                     {"xi-Inelastic", 79},
    //                                                     {"xi0Inelastic", 80},
    //                                                     {"xi_b-Inelastic", 81},
    //                                                     {"xi_b0Inelastic", 82},
    //                                                     {"xi_c+Inelastic", 83},
    //                                                     {"xi_c0Inelastic", 84},
    //                                                 };
};

#endif
